include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE=release

LUCI_TITLE:=LuCI Support for mihomo
LUCI_DEPENDS:=+luci-base

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature