include $(TOPDIR)/rules.mk

PKG_VERSION:=$(LUCI_APP_MIHOMO_PKG_VERSION)

LUCI_TITLE:=LuCI Support for mihomo
LUCI_DEPENDS:=+luci-base +mihomo

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature