name: build-packages

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_vfpv3-d16
          - arm_cortex-a9_neon
          - arm_cortex-a15_neon-vfpv4
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - mips64_octeonplus
          - riscv64_riscv64
          - riscv64_generic
          - loongarch64_generic
          - i386_pentium4
          - x86_64
        branch:
          - openwrt-24.10
          - openwrt-25.12
          - SNAPSHOT
        exclude:
          - arch: mips_4kec
            branch: openwrt-25.12
          - arch: mips_4kec
            branch: SNAPSHOT
          - arch: riscv64_riscv64
            branch: openwrt-25.12
          - arch: riscv64_riscv64
            branch: SNAPSHOT
          - arch: riscv64_generic
            branch: openwrt-24.10

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: mihomo-alpha mihomo-meta nikki-geodata nikki luci-app-nikki
          NO_REFRESH_CHECK: true

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/nikki
