name: release-packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    name: ${{ matrix.arch }}-${{ matrix.branch }} release
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_vfpv3-d16
          - arm_cortex-a9_neon
          - arm_cortex-a15_neon-vfpv4
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - mips64_octeonplus
          - riscv64_riscv64
          - riscv64_generic
          - loongarch64_generic
          - i386_pentium4
          - x86_64
        branch:
          - openwrt-24.10
          - openwrt-25.12
          - SNAPSHOT
        exclude:
          - arch: mips_4kec
            branch: openwrt-25.12
          - arch: mips_4kec
            branch: SNAPSHOT
          - arch: riscv64_riscv64
            branch: openwrt-25.12
          - arch: riscv64_riscv64
            branch: SNAPSHOT
          - arch: riscv64_generic
            branch: openwrt-24.10

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: mihomo-alpha mihomo-meta nikki-geodata nikki luci-app-nikki
          INDEX: 1
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NO_REFRESH_CHECK: true

      - name: compress
        run: |
          tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C bin/packages/${{ matrix.arch }}/nikki .
          mkdir -p public/${{ matrix.branch }}/${{ matrix.arch }}
          mv bin/packages/${{ matrix.arch }}/nikki public/${{ matrix.branch }}/${{ matrix.arch }}
          tar -c -z -f feed_nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz public/${{ matrix.branch }}/${{ matrix.arch }}

      - if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
        name: release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: feed_nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: feed_nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz

  feed:
    needs: release
    name: feed
    runs-on: ubuntu-latest

    steps:
      - name: download
        uses: actions/download-artifact@v8
        with:
          pattern: feed_nikki_*
          merge-multiple: true
      
      - name: uncompress
        run: |
          for file in feed_nikki_*.tar.gz; do tar -x -z -f "$file"; done
      
      - name: prepare
        run: |
          echo "${{ secrets.KEY_BUILD_PUB }}" > public/key-build.pub
          echo "${{ secrets.PUBLIC_KEY }}" > public/public-key.pem
          tree --dirsfirst --sort name -P '*.apk|*.ipk' --prune --noreport -H "" -T "Nikki's Feed" --charset utf-8 -o public/index.html public
          sed -i '/<p class="VERSION">/,/<\/p>/d' public/index.html

      - name: feed
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy public --project-name=nikkinikki
